Fix null socials handling (#53)
Add null type to Socials since missing JSON field deserializes to null. I'm able to deploy locally, so this will fix the deployment error from the CI:

```
   Linting and checking validity of types ...
Failed to compile.
./pages/_app.tsx:24:16
Type error: Conversion of type '{ name: string; favicon: null; navigation: ({ type: string; title: string; path: string; section: null; contents?: undefined; } | { type: string; title: string; contents: ({ type: string; title: string; relative_path: string; apis: string[]; section: string; path?: undefined; } | { ...; })[]; path?: undefined; secti...' to type 'Config' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'socials' are incompatible.
    Type 'null' is not comparable to type 'Social[] | undefined'.
  22 | import configData from "../data/config.json";
  23 | import { Config, Tab, NavigationItem } from "../types/config";
> 24 | const config = configData as Config;
     |                ^
  25 |
  26 | import { TableOfContentsItem } from "../components/TableOfContents";
  27 | import { Page, Reference } from "../types/config";
Error: Command "npm run build" exited with 1
```